# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-12 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='city',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='country',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='father_contectNo',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='father_email',
            field=models.EmailField(default='sks@yahoo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='father_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='mother_contectNo',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='mother_email',
            field=models.EmailField(default='as@yahoo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='mother_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
